 - name: install mysql
   ansible.builtin.package:
    name: mysql-server
    state:  present

 - name: enable and start service
   ansible.builtin.service:
    name: mysqld
    enabled:  yes
    state:  started

 -  name: install boto3 and botocore
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore

 - name: setting root pass
   ansible.builtin.command:  mysql_secure_installation --set-root-pass {{   MYSQL_ROOT_PASSWORD }}
 